server:
  port: 9959
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      encoding: UTF-8
      mode: always
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden-method:
      filter:
        enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-operation-id: true
    display-request-duration: true